// apps/stencil-sample/src/components/data-example/data-example.tsx
import { Component, Prop, State, h } from '@stencil/core';
import { DataExampleViewModel } from '@headless/models';
import { Data, applyValues } from '@headless/core';
import { initViewModel } from '@headless/core/src/models';

@Component({
  tag: 'data-example',
  styleUrl: 'data-example.css',
  shadow: false,
})
export class DataExample {
  private actions: Record<string, () => void>;

  @State() data: Data;

  getData() {
    return this.data;
  }

  updateData(values: Data) {
    this.data = applyValues(this.getData(), values);
  }

  componentWillLoad() {
    Object.assign(this, initViewModel(DataExampleViewModel, {
      getData: this.getData.bind(this),
      updateData: this.updateData.bind(this),
    }, () => ({})));
  }

  render() {
    const { data, actions } = this;

    return (
      <div class="card">
        <h2>Data Example</h2>
        <button type="button" onClick={actions.increment}>
          count is {data.count}
        </button>
      </div>
    );
  }
}

// apps/vue-sample/src/components/DataExample.tsx
import { defineComponent, FunctionalComponent } from 'vue';
import { DataExampleViewModel } from '@headless/models';
import { useViewModel } from '../libs/vueUtils';

export const DataExample = defineComponent({
  setup() {
    const { getData, actions } = useViewModel(DataExampleViewModel, {});

    return () => {
      const { count } = getData();

      return (
        <div className="card">
          <h2>Data Example</h2>
          <button type="button" onClick={actions.increment}>
            count is {count as number}
          </button>
        </div>
      );
    };
  },
}) as unknown as FunctionalComponent;

export default DataExample;
