// apps/react-sample/src/components/DataExample.tsx
import { DataExampleViewModel } from '@headless/models';
import { useViewModel } from '../libs/reactUtils';
import { TestButton } from '.';

export function DataExample() {
  const {
    actions: {increment},
    data: { count },
  } = useViewModel(DataExampleViewModel, {});

  return (
    <div className="card">
      <h2>Data Example</h2>
      <TestButton action={increment}>
        count is {count as number}
      </TestButton>
    </div>
  );
}

export default DataExample;

// apps/vue-sample/src/components/DataExample.tsx
import { defineComponent, FunctionalComponent } from 'vue';
import { DataExampleViewModel } from '@headless/models';
import { useViewModel } from '../libs/vueUtils';

export const DataExample = defineComponent({
  setup() {
    const { getData, actions } = useViewModel(DataExampleViewModel, {});

    return () => {
      const { count } = getData();

      return (
        <div className="card">
          <h2>Data Example</h2>
          <button type="button" onClick={actions.increment}>
            count is {count as number}
          </button>
        </div>
      );
    };
  },
}) as unknown as FunctionalComponent;

export default DataExample;
